// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT7cSy5QsNN_HtQZG09IhBwwdSqqoQy7I',
    appId: '1:682669041684:web:678fb4033b8dde3ddadf01',
    messagingSenderId: '682669041684',
    projectId: 'girlshouseapp',
    authDomain: 'girlshouseapp.firebaseapp.com',
    storageBucket: 'girlshouseapp.appspot.com',
    measurementId: 'G-WF8K90BNDE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9cWzfufM0YZJZrWnKKuMZ83SDo4o8EYY',
    appId: '1:682669041684:android:8fb3de7993187833dadf01',
    messagingSenderId: '682669041684',
    projectId: 'girlshouseapp',
    storageBucket: 'girlshouseapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAC8R4IUKjruCzGlb8Me_H9cCdFDnty4AU',
    appId: '1:682669041684:ios:f7d60e98467b8439dadf01',
    messagingSenderId: '682669041684',
    projectId: 'girlshouseapp',
    storageBucket: 'girlshouseapp.appspot.com',
    iosClientId: '682669041684-o2gs1dlkg3fi75doghb47kemqp5lekem.apps.googleusercontent.com',
    iosBundleId: 'com.example.girlsHouseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC8R4IUKjruCzGlb8Me_H9cCdFDnty4AU',
    appId: '1:682669041684:ios:636ea9976e5dcdcbdadf01',
    messagingSenderId: '682669041684',
    projectId: 'girlshouseapp',
    storageBucket: 'girlshouseapp.appspot.com',
    iosClientId: '682669041684-p23mff37ehgkjkcogli45io3qg09bin4.apps.googleusercontent.com',
    iosBundleId: 'com.example.girlsHouseApp.RunnerTests',
  );
}
